name: Docker Image Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Azure Container Registry Login
      run: |
        docker login -u github -p ${{ secrets.ACR_PASSWORD }} clientgpt.azurecr.io

    - uses: actions/checkout@v3

    - name: Build and Push Docker image
      run: |
        set -e
        docker build . --file WebApp.Dockerfile --tag clientgpt.azurecr.io/internalclientgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag clientgpt.azurecr.io/internalclientgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER clientgpt.azurecr.io/internalclientgpt:latest;
        docker push clientgpt.azurecr.io/internalclientgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push clientgpt.azurecr.io/internalclientgpt:latest;
