name: Build and deploy container app to Azure Web App - zerodosegpt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Convert username to lowercase
      run: echo "ACR_USERNAME=$(echo ${{ secrets.AzureAppService_ContainerUsername_3554df6cd93245b6957a554156889c2d }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://clientgpt.azurecr.io/
        username: ${{ env.ACR_USERNAME }}
        password: ${{ secrets.AzureAppService_ContainerPassword_593e4471a3cf46f7a135613a886b5ee1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: clientgpt.azurecr.io/${{ env.ACR_USERNAME }}/clientgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'zerodosegpt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_48f9600c5f414e3abc971048c3944a22 }}
        images: 'clientgpt.azurecr.io/${{ env.ACR_USERNAME }}/clientgpt:${{ github.sha }}'
