name: Build and deploy container app to Azure Web App - zerodosegpt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      run: |
        docker login -u github -p ${{ secrets.AzureAppService_ContainerPassword_9bb6ac2427cd4cc5a492912b583bc4fa }} clientgpt.azurecr.io

    - name: Build and push container image to registry
      run: |
        docker build . --file Dockerfile --tag clientgpt.azurecr.io/internalclientgpt:${{ github.sha }}
        docker tag clientgpt.azurecr.io/internalclientgpt:${{ github.sha }} clientgpt.azurecr.io/internalclientgpt:latest
        docker push clientgpt.azurecr.io/internalclientgpt:${{ github.sha }}
        docker push clientgpt.azurecr.io/internalclientgpt:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'zerodosegpt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5b6a7b12b918404f9db227be05deedfb }}
        images: 'clientgpt.azurecr.io/internalclientgpt:latest'
