name: Build and deploy container app to Azure Web App - zerodosegpt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Convert username to lowercase
      run: echo "ACR_USERNAME=$(echo ${{ secrets.AzureAppService_ContainerUsername_79530c1df2c342e499cc6791990df6bf }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://clientgpt.azurecr.io/
        username: ${{ env.ACR_USERNAME }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9bb6ac2427cd4cc5a492912b583bc4fa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: clientgpt.azurecr.io/${{ env.ACR_USERNAME }}/internalgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'zerodosegpt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5b6a7b12b918404f9db227be05deedfb }}
        images: 'clientgpt.azurecr.io/${{ env.ACR_USERNAME }}/internalgpt:${{ github.sha }}'
